# Generated by Django 4.0.3 on 2022-04-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursoApp', '0004_alter_preguntasrespondida_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondida',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='concursoApp.elegirrespuesta'),
        ),
    ]
