# Generated by Django 4.0.3 on 2022-04-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursoApp', '0005_alter_preguntasrespondida_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondida',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concursoApp.elegirrespuesta'),
        ),
    ]
