# Generated by Django 4.0.3 on 2022-04-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursoApp', '0006_alter_preguntasrespondida_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondida',
            name='puntajeObtenido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Puntaje obtenido'),
        ),
    ]
